/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/cash': RouteRecordInfo<'/cash', '/cash', Record<never, never>, Record<never, never>, '/cash/' | '/cash/[tableId]'>,
    '/cash/': RouteRecordInfo<'/cash/', '/cash', Record<never, never>, Record<never, never>>,
    '/cash/[tableId]': RouteRecordInfo<'/cash/[tableId]', '/cash/:tableId', { tableId: ParamValue<true> }, { tableId: ParamValue<false> }>,
    '/error': RouteRecordInfo<'/error', '/error', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/name-input': RouteRecordInfo<'/name-input', '/name-input', Record<never, never>, Record<never, never>>,
    '/onboarding': RouteRecordInfo<'/onboarding', '/onboarding', Record<never, never>, Record<never, never>>,
    '/order': RouteRecordInfo<'/order', '/order', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/cash.vue': {
      routes: '/cash' | '/cash/' | '/cash/[tableId]'
      views: 'default'
    }
    'src/pages/cash@AppBarExtension.vue': {
      routes: '/cash' | '/cash/' | '/cash/[tableId]'
      views: 'default'
    }
    'src/pages/cash/index.vue': {
      routes: '/cash/'
      views: never
    }
    'src/pages/cash/[tableId].vue': {
      routes: '/cash/[tableId]'
      views: never
    }
    'src/pages/error.vue': {
      routes: '/error'
      views: never
    }
    'src/pages/home.vue': {
      routes: '/home'
      views: never
    }
    'src/pages/NameInput.vue': {
      routes: '/name-input'
      views: never
    }
    'src/pages/onboarding.vue': {
      routes: '/onboarding'
      views: never
    }
    'src/pages/order.vue': {
      routes: '/order'
      views: never
    }
    'src/pages/order@AppBarExtension.vue': {
      routes: '/order'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
