/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BaseItem: typeof import('./components/Subscriptions/BaseItem.vue')['default']
    BaseItemsServiceTable: typeof import('./components/ServiceTables/BaseItemsServiceTable.vue')['default']
    ButtonCollection: typeof import('./components/Calculator/ButtonCollection.vue')['default']
    'Calculator@AppBar': typeof import('./components/Calculator/calculator@AppBar.vue')['default']
    'Calculator@AppBarAppendix': typeof import('./components/Calculator/calculator@AppBarAppendix.vue')['default']
    'Calculator@AppBarComponent': typeof import('./components/Calculator/calculator@AppBarComponent.vue')['default']
    'Calculator@AppBarExtension': typeof import('./components/Calculator/calculator@AppBarExtension.vue')['default']
    CategoriesServiceTable: typeof import('./components/ServiceTables/CategoriesServiceTable.vue')['default']
    Category: typeof import('./components/Subscriptions/Category.vue')['default']
    ConfigurationMenu: typeof import('./components/Calculator/ConfigurationMenu.vue')['default']
    DataReview: typeof import('./components/DataExchange/DataReview.vue')['default']
    DataSelection: typeof import('./components/DataExchange/DataSelection.vue')['default']
    DatePicker: typeof import('./components/Utilities/DatePicker.vue')['default']
    Export: typeof import('./components/Statistics/Export.vue')['default']
    ExportPreview: typeof import('./components/DataExchange/ExportPreview.vue')['default']
    FileInformation: typeof import('./components/DataExchange/FileInformation.vue')['default']
    FileInput: typeof import('./components/DataExchange/FileInput.vue')['default']
    FlavoursServiceTable: typeof import('./components/ServiceTables/FlavoursServiceTable.vue')['default']
    HeaderMapper: typeof import('./components/DataExchange/HeaderMapper.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ImportHelper: typeof import('./components/DataExchange/ImportHelper.vue')['default']
    ItemsServiceTable: typeof import('./components/ServiceTables/ItemsServiceTable.vue')['default']
    KeybindingDialog: typeof import('./components/Keybindings/KeybindingDialog.vue')['default']
    Loading: typeof import('./components/Utilities/Loading.vue')['default']
    MixedLayout: typeof import('./components/Calculator/MixedLayout.vue')['default']
    MixedWrapper: typeof import('./components/Calculator/MixedWrapper.vue')['default']
    NavigationListItem: typeof import('./components/Utilities/NavigationListItem.vue')['default']
    NewItemDialog: typeof import('./components/ServiceTables/NewItemDialog.vue')['default']
    Notification: typeof import('./components/Utilities/Notification.vue')['default']
    OrderCard: typeof import('./components/ItemPreparation/OrderCard.vue')['default']
    OrderDialog: typeof import('./components/Calculator/OrderDialog.vue')['default']
    OrderedItemsServiceTable: typeof import('./components/ServiceTables/OrderedItemsServiceTable.vue')['default']
    OrderListItem: typeof import('./components/ItemPreparation/OrderListItem.vue')['default']
    OrdersServiceTable: typeof import('./components/ServiceTables/OrdersServiceTable.vue')['default']
    OrderWrapper: typeof import('./components/ItemPreparation/OrderWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeparatedWrapper: typeof import('./components/Calculator/SeparatedWrapper.vue')['default']
    ShoppingCartSum: typeof import('./components/Calculator/ShoppingCartSum.vue')['default']
    SingleBaseItem: typeof import('./components/Calculator/SingleBaseItem.vue')['default']
    SingleCategory: typeof import('./components/Calculator/SingleCategory.vue')['default']
    SingleItem: typeof import('./components/Calculator/SingleItem.vue')['default']
    SizesServiceTable: typeof import('./components/ServiceTables/SizesServiceTable.vue')['default']
    TablesServiceTabl: typeof import('./components/ServiceTables/TablesServiceTabl.vue')['default']
    TimePicker: typeof import('./components/Utilities/TimePicker.vue')['default']
    Void: typeof import('./components/svg/Void.vue')['default']
  }
}
