/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/(calculator)/calculator': RouteRecordInfo<'/(calculator)/calculator', '/calculator', Record<never, never>, Record<never, never>>,
    '/config': RouteRecordInfo<'/config', '/config', Record<never, never>, Record<never, never>>,
    '/data-exchange': RouteRecordInfo<'/data-exchange', '/data-exchange', Record<never, never>, Record<never, never>, '/DataExchange/export' | '/DataExchange/import' | '/data-exchange/'>,
    '/data-exchange/': RouteRecordInfo<'/data-exchange/', '/data-exchange', Record<never, never>, Record<never, never>>,
    '/DataExchange/export': RouteRecordInfo<'/DataExchange/export', '/data-exchange/export', Record<never, never>, Record<never, never>>,
    '/DataExchange/import': RouteRecordInfo<'/DataExchange/import', '/data-exchange/import', Record<never, never>, Record<never, never>>,
    '/error': RouteRecordInfo<'/error', '/error', Record<never, never>, Record<never, never>>,
    '/history': RouteRecordInfo<'/history', '/history', Record<never, never>, Record<never, never>>,
    '/item-manager': RouteRecordInfo<'/item-manager', '/item-manager', Record<never, never>, Record<never, never>>,
    '/keybindings': RouteRecordInfo<'/keybindings', '/keybindings', Record<never, never>, Record<never, never>>,
    '/main': RouteRecordInfo<'/main', '/main', Record<never, never>, Record<never, never>>,
    '/onboarding': RouteRecordInfo<'/onboarding', '/onboarding', Record<never, never>, Record<never, never>>,
    '/statistics': RouteRecordInfo<'/statistics', '/statistics', Record<never, never>, Record<never, never>>,
    '/subscriptions': RouteRecordInfo<'/subscriptions', '/subscriptions', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/(calculator)/calculator.vue': {
      routes: '/(calculator)/calculator'
      views: never
    }
    'src/pages/(calculator)/calculator@AppBarAppendix.vue': {
      routes: '/(calculator)/calculator'
      views: never
    }
    'src/pages/(calculator)/calculator@AppBarComponent.vue': {
      routes: '/(calculator)/calculator'
      views: never
    }
    'src/pages/(calculator)/calculator@AppBarExtension.vue': {
      routes: '/(calculator)/calculator'
      views: never
    }
    'src/pages/config.vue': {
      routes: '/config'
      views: never
    }
    'src/pages/config@AppBarComponent.vue': {
      routes: '/config'
      views: never
    }
    'src/pages/DataExchange.vue': {
      routes: '/data-exchange' | '/data-exchange/' | '/DataExchange/export' | '/DataExchange/import'
      views: 'default'
    }
    'src/pages/DataExchange/index.vue': {
      routes: '/data-exchange/'
      views: never
    }
    'src/pages/DataExchange/export.vue': {
      routes: '/DataExchange/export'
      views: never
    }
    'src/pages/DataExchange/import.vue': {
      routes: '/DataExchange/import'
      views: never
    }
    'src/pages/error.vue': {
      routes: '/error'
      views: never
    }
    'src/pages/history.vue': {
      routes: '/history'
      views: never
    }
    'src/pages/ItemManager.vue': {
      routes: '/item-manager'
      views: never
    }
    'src/pages/keybindings.vue': {
      routes: '/keybindings'
      views: never
    }
    'src/pages/main.vue': {
      routes: '/main'
      views: never
    }
    'src/pages/main@AppBarComponent.vue': {
      routes: '/main'
      views: never
    }
    'src/pages/onboarding.vue': {
      routes: '/onboarding'
      views: never
    }
    'src/pages/statistics.vue': {
      routes: '/statistics'
      views: never
    }
    'src/pages/subscriptions.vue': {
      routes: '/subscriptions'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
